"use client";

import { useQuery } from "@tanstack/react-query";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Analytics = { channels: Array<{ channel: string; messages: number; delivered: number; opened: number; clicked: number }>; segments: Array<{ name: string; customers: number; messages: number; clicked: number; clickRate: number }>; attribution: Array<{ id: string; name: string; channel: string; conversions: number; revenue: number }> };
type Decisioning = { modelVersion: string; audienceSize: number; expectedRevenue: number; highChurnRisk: number; benchmark: { selected: number; ai: { precision: number; revenue: number }; random: { precision: number; revenue: number }; uplift: { precisionPercent: number; revenuePercent: number } }; recommendations: Array<{ customerId: string; name: string; decisionScore: number; expectedRevenue: number; churnRisk: number; recommendedChannel: string; recommendedSendHour: number; reasons: string[] }> };

export default function AnalyticsPage(): JSX.Element {
  const { data } = useQuery<Analytics>({ queryKey: ["analytics"], queryFn: async () => { const response = await fetch("/api/analytics"); if (!response.ok) throw new Error("Unable to load analytics"); return response.json() as Promise<Analytics>; } });
  const { data: decisioning } = useQuery<Decisioning>({ queryKey: ["decisioning"], queryFn: async () => { const response = await fetch("/api/decisioning"); if (!response.ok) throw new Error("Unable to load decision model"); return response.json() as Promise<Decisioning>; } });
  return <div className="space-y-6"><header><p className="label mb-2">Performance and decision science</p><h1 className="text-3xl font-semibold">Analytics</h1><p className="mt-1 text-sm text-[#64716c]">Causal campaign results, model benchmarks, audience risk, and attributed revenue.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="panel p-5"><span className="label">Scored customers</span><strong className="mt-2 block text-3xl">{decisioning?.audienceSize ?? "-"}</strong><p className="text-xs text-[#71807a]">Model {decisioning?.modelVersion ?? "loading"}</p></article><article className="panel p-5"><span className="label">Expected revenue</span><strong className="mt-2 block text-3xl">${decisioning?.expectedRevenue.toFixed(0) ?? "-"}</strong><p className="text-xs text-[#71807a]">Probability-weighted estimate</p></article><article className="panel p-5"><span className="label">High churn risk</span><strong className="mt-2 block text-3xl">{decisioning?.highChurnRisk ?? "-"}</strong><p className="text-xs text-[#71807a]">Risk score at or above 70%</p></article><article className="panel p-5"><span className="label">AI vs random revenue</span><strong className="mt-2 block text-3xl">{decisioning ? `${decisioning.benchmark.uplift.revenuePercent.toFixed(0)}%` : "-"}</strong><p className="text-xs text-[#71807a]">Seeded offline top-{decisioning?.benchmark.selected ?? "k"} benchmark</p></article></section>
    <section className="grid gap-4 lg:grid-cols-[1.2fr_1fr]"><article className="panel p-5"><h2 className="font-semibold">Offline targeting benchmark</h2><p className="mt-1 text-xs text-[#71807a]">Historical conversions only. Use randomized experiments for causal claims.</p><div className="mt-5 grid grid-cols-2 gap-4"><div className="rounded-md bg-[#eaf5f0] p-4"><span className="label">Decision model</span><strong className="mt-2 block text-2xl">{decisioning ? `${(decisioning.benchmark.ai.precision * 100).toFixed(1)}%` : "-"}</strong><p className="text-xs text-[#64716c]">Precision, ${decisioning?.benchmark.ai.revenue.toFixed(0) ?? 0} observed revenue</p></div><div className="rounded-md bg-[#f2f5f3] p-4"><span className="label">Seeded random</span><strong className="mt-2 block text-2xl">{decisioning ? `${(decisioning.benchmark.random.precision * 100).toFixed(1)}%` : "-"}</strong><p className="text-xs text-[#64716c]">Precision, ${decisioning?.benchmark.random.revenue.toFixed(0) ?? 0} observed revenue</p></div></div></article><article className="panel p-5"><h2 className="font-semibold">Channel performance</h2><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data?.channels ?? []}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="channel" /><YAxis /><Tooltip /><Legend /><Bar dataKey="delivered" fill="#147d64" /><Bar dataKey="opened" fill="#d7a33d" /><Bar dataKey="clicked" fill="#d9674f" /></BarChart></ResponsiveContainer></div></article></section>
    <section className="panel overflow-hidden"><div className="border-b border-line px-5 py-4"><h2 className="font-semibold">Top customer recommendations</h2><p className="text-xs text-[#71807a]">Ranked by estimated conversion probability with frozen explanations.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#f2f5f3] text-xs uppercase text-[#66736e]"><tr><th className="px-5 py-3">Customer</th><th>Score</th><th>Expected revenue</th><th>Churn</th><th>Channel / hour</th><th>Primary reason</th></tr></thead><tbody className="divide-y divide-line">{decisioning?.recommendations.slice(0, 10).map((item) => <tr key={item.customerId}><td className="px-5 py-4 font-semibold">{item.name}</td><td>{item.decisionScore.toFixed(1)}</td><td>${item.expectedRevenue.toFixed(2)}</td><td>{Math.round(item.churnRisk * 100)}%</td><td>{item.recommendedChannel} at {item.recommendedSendHour}:00</td><td className="max-w-xs text-[#64716c]">{item.reasons[0]}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><article className="panel overflow-hidden"><div className="border-b border-line px-5 py-4"><h2 className="font-semibold">Best performing segments</h2></div><table className="w-full text-left text-sm"><thead className="bg-[#f2f5f3] text-xs uppercase text-[#66736e]"><tr><th className="px-5 py-3">Segment</th><th>Customers</th><th>Click rate</th></tr></thead><tbody className="divide-y divide-line">{data?.segments.map((segment) => <tr key={segment.name}><td className="px-5 py-4 font-semibold">{segment.name}</td><td>{segment.customers}</td><td>{segment.clickRate}%</td></tr>)}</tbody></table></article><article className="panel overflow-hidden"><div className="border-b border-line px-5 py-4"><h2 className="font-semibold">Conversion attribution</h2></div><div className="divide-y divide-line">{data?.attribution.map((campaign) => <div key={campaign.id} className="grid grid-cols-[1fr_90px_100px] px-5 py-4 text-sm"><div><strong>{campaign.name}</strong><p className="text-xs text-[#71807a]">{campaign.channel}</p></div><span>{campaign.conversions} orders</span><strong>${campaign.revenue.toFixed(2)}</strong></div>)}</div></article></section></div>;
}
