"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Radio } from "lucide-react";
import { useParams } from "next/navigation";
import { useEffect } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Badge } from "../../../components/ui/badge";

type Stats = { campaign: { name: string; status: string; channel: string; messageTemplate: string; failureReason: string | null }; counts: Record<string, number>; conversions: number; revenue: number; providerCost: number; decisioning: { averageScore: number; averageChurnRisk: number; expectedRevenue: number }; experiment: null | { hypothesis: string; status: string; variants: Array<{ kind: string; name: string; recipients: number; conversions: number; revenue: number }>; result: null | { controlRate: number; treatmentRate: number; upliftPercent: number; confidence: number; significant: boolean; winner: string } } };
const statuses = ["SENT", "DELIVERED", "OPENED", "READ", "CLICKED"];

export default function CampaignDetailPage(): JSX.Element {
  const params = useParams<{ id: string }>();
  const queryClient = useQueryClient();
  const { data, isLoading } = useQuery<Stats>({ queryKey: ["campaign", params.id], queryFn: async () => { const response = await fetch(`/api/campaigns/${params.id}/stats`); if (!response.ok) throw new Error("Unable to load campaign"); return response.json() as Promise<Stats>; }, refetchInterval: () => document.visibilityState === "visible" ? 5_000 : false });
  useEffect(() => { let socket: WebSocket | undefined; let cancelled = false; void fetch("/api/realtime/token", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ campaignId: params.id }) }).then(async (response) => response.json() as Promise<{ token?: string }>).then(({ token }) => { if (!token || cancelled) return; const protocol = window.location.protocol === "https:" ? "wss" : "ws"; socket = new WebSocket(`${protocol}://${window.location.hostname}:3001?token=${encodeURIComponent(token)}`); socket.onmessage = () => void queryClient.invalidateQueries({ queryKey: ["campaign", params.id] }); }); return () => { cancelled = true; socket?.close(); }; }, [params.id, queryClient]);
  if (isLoading || !data) return <p>Loading campaign...</p>;
  const chartData = statuses.map((status) => ({ status, messages: data.counts[status] ?? 0 }));
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="label mb-2">{data.campaign.channel}</p><h1 className="text-3xl font-semibold">{data.campaign.name}</h1><div className="mt-2 flex items-center gap-2"><Badge>{data.campaign.status}</Badge><span className="inline-flex items-center gap-1 text-xs font-semibold text-accent"><Radio size={13} /> WebSocket live receipts</span></div>{data.campaign.failureReason ? <p className="mt-2 text-sm text-red-700">{data.campaign.failureReason}</p> : null}</div><a className="btn" href={`/api/campaigns/${params.id}/export`} download><Download size={16} /> Export CSV</a></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="panel p-5"><span className="label">Messages</span><strong className="mt-2 block text-3xl">{Object.values(data.counts).reduce((sum, count) => sum + count, 0)}</strong></article><article className="panel p-5"><span className="label">Conversions</span><strong className="mt-2 block text-3xl">{data.conversions}</strong></article><article className="panel p-5"><span className="label">Revenue</span><strong className="mt-2 block text-3xl">${data.revenue.toFixed(2)}</strong></article><article className="panel p-5"><span className="label">Provider cost / ROI</span><strong className="mt-2 block text-3xl">${data.providerCost.toFixed(2)}</strong><p className="text-xs text-[#71807a]">{data.providerCost ? `${((data.revenue - data.providerCost) / data.providerCost * 100).toFixed(0)}% ROI` : "No billable sends yet"}</p></article></section>
    <section className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><article className="panel p-5"><h2 className="font-semibold">Delivery funnel</h2><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="status" fontSize={11} /><YAxis fontSize={11} /><Tooltip /><Bar dataKey="messages" fill="#147d64" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></article><article className="panel p-5"><h2 className="font-semibold">Message preview</h2><div className="mt-5 rounded-md bg-[#edf3f0] p-4 text-sm leading-6">{data.campaign.messageTemplate.replace("{{name}}", "Maya").replace("{{lastProduct}}", "Vitamin C Serum")}</div></article></section>
    <section className="grid gap-4 md:grid-cols-3"><article className="panel p-5"><span className="label">Average decision score</span><strong className="mt-2 block text-3xl">{data.decisioning.averageScore.toFixed(1)}</strong><p className="text-xs text-[#71807a]">Estimated conversion propensity</p></article><article className="panel p-5"><span className="label">Audience churn risk</span><strong className="mt-2 block text-3xl">{Math.round(data.decisioning.averageChurnRisk * 100)}%</strong><p className="text-xs text-[#71807a]">Explainable RFM risk estimate</p></article><article className="panel p-5"><span className="label">Expected revenue</span><strong className="mt-2 block text-3xl">${data.decisioning.expectedRevenue.toFixed(2)}</strong><p className="text-xs text-[#71807a]">Pre-send model estimate</p></article></section>
    {data.experiment && <section className="panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="label mb-2">Randomized experiment</p><h2 className="font-semibold">{data.experiment.hypothesis}</h2></div><Badge>{data.experiment.status}</Badge></div><div className="mt-5 grid gap-4 md:grid-cols-2">{data.experiment.variants.map((variant) => <article key={variant.kind} className="rounded-md border border-line p-4"><span className="label">{variant.name}</span><div className="mt-3 grid grid-cols-3 gap-3 text-sm"><div><strong className="block text-xl">{variant.recipients}</strong><span className="text-[#71807a]">Recipients</span></div><div><strong className="block text-xl">{variant.conversions}</strong><span className="text-[#71807a]">Conversions</span></div><div><strong className="block text-xl">${variant.revenue.toFixed(0)}</strong><span className="text-[#71807a]">Revenue</span></div></div></article>)}</div>{data.experiment.result && <div className="mt-4 rounded-md bg-[#f2f5f3] p-4 text-sm"><strong>{data.experiment.result.upliftPercent.toFixed(1)}% conversion uplift</strong><span className="ml-2 text-[#64716c]">{Math.round(data.experiment.result.confidence * 100)}% confidence. {data.experiment.result.significant ? `${data.experiment.result.winner} is statistically significant.` : "More observations are required before declaring a winner."}</span></div>}</section>}
  </div>;
}
