"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CalendarClock, Check, Mail, MessageCircle, Send } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { AIChatSidebar } from "../../../components/ai/ai-chat-sidebar";

type Segment = { id: string; name: string; description: string; customerCount: number };
type Preview = { count: number; customers: Array<{ id: string; name: string; city: string; totalOrderValue: string; channelPreference: string }> };
const channels = [{ value: "WHATSAPP", icon: MessageCircle }, { value: "SMS", icon: Send }, { value: "EMAIL", icon: Mail }, { value: "RCS", icon: MessageCircle }] as const;
type Channel = typeof channels[number]["value"];

function isChannel(value: string): value is Channel { return channels.some((item) => item.value === value); }

export default function NewCampaignPage(): JSX.Element {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [step, setStep] = useState(1);
  const [segmentId, setSegmentId] = useState("");
  const [channel, setChannel] = useState<Channel>("WHATSAPP");
  const [name, setName] = useState("Personalized re-engagement");
  const [message, setMessage] = useState("Hi {{name}}, we saved something special for you. Revisit {{lastProduct}} today.");
  const [scheduleMode, setScheduleMode] = useState<"now" | "later">("now");
  const [scheduledAt, setScheduledAt] = useState("");
  const [submitError, setSubmitError] = useState("");
  const [experimentEnabled, setExperimentEnabled] = useState(true);
  const [hypothesis, setHypothesis] = useState("A benefit-led AI message will increase conversion rate versus the standard message.");
  const [treatmentMessage, setTreatmentMessage] = useState("Hi {{name}}, based on your interest in {{lastProduct}}, this offer was selected for you. Shop before it expires.");
  const [scoreTargeting, setScoreTargeting] = useState(true);
  const [targetPercentage, setTargetPercentage] = useState(30);
  const [recommendedChannel, setRecommendedChannel] = useState(true);
  const [recommendedTime, setRecommendedTime] = useState(true);
  const { data: segments = [] } = useQuery<Segment[]>({ queryKey: ["segments"], queryFn: async () => (await fetch("/api/segments")).json() as Promise<Segment[]> });
  const selected = segments.find((segment) => segment.id === segmentId);
  const { data: preview } = useQuery<Preview>({ queryKey: ["segment-preview", segmentId], enabled: Boolean(segmentId), queryFn: async () => { const response = await fetch(`/api/segments/${segmentId}/preview`); if (!response.ok) throw new Error("Unable to preview segment"); return response.json() as Promise<Preview>; } });
  useEffect(() => { if (selected) setName(`${selected.name} campaign`); }, [selected]);
  const create = useMutation({
    mutationFn: async () => {
      setSubmitError("");
      const createResponse = await fetch("/api/campaigns", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, segmentId, channel, messageTemplate: message, scheduledAt: scheduleMode === "later" && scheduledAt ? new Date(scheduledAt).toISOString() : null, aiGenerated: false, targetingMode: scoreTargeting ? "SCORE_TOP_PERCENT" : "ALL", targetPercentage: scoreTargeting ? targetPercentage : 100, useRecommendedChannel: recommendedChannel, useRecommendedSendTime: recommendedTime, experiment: experimentEnabled ? { hypothesis, treatmentTemplate: treatmentMessage, controlAllocation: 50 } : undefined }) });
      const campaign = await createResponse.json() as { id?: string; error?: string };
      if (!createResponse.ok || !campaign.id) throw new Error(campaign.error ?? "Unable to create campaign");
      queryClient.setQueryData(["campaign", campaign.id], { campaign: { name, status: "RUNNING", channel, messageTemplate: message }, counts: { QUEUED: preview?.count ?? selected?.customerCount ?? 0 }, conversions: 0, revenue: 0 });
      const launchResponse = await fetch(`/api/campaigns/${campaign.id}/launch`, { method: "POST" });
      const launched = await launchResponse.json() as { error?: string };
      if (!launchResponse.ok) throw new Error(launched.error ?? "Campaign launch failed");
      return { id: campaign.id };
    },
    onSuccess: (campaign) => router.push(`/campaigns/${campaign.id}`),
    onError: (error) => setSubmitError(error instanceof Error ? error.message : "Campaign launch failed")
  });
  return <div className="space-y-6"><header><p className="label mb-2">Campaign builder</p><h1 className="text-3xl font-semibold">Create campaign</h1><div className="mt-5 flex flex-wrap gap-2">{["Audience", "Message", "Review", "Launch"].map((label, index) => <div key={label} className={`flex items-center gap-2 text-sm ${step >= index + 1 ? "font-semibold text-accent" : "text-[#8a9591]"}`}><span className={`grid size-6 place-items-center rounded-full border ${step > index + 1 ? "border-accent bg-accent text-white" : "border-current"}`}>{step > index + 1 ? <Check size={13} /> : index + 1}</span>{label}{index < 3 && <span className="mx-2 h-px w-10 bg-line" />}</div>)}</div></header>
    <div className="grid overflow-hidden rounded-lg border border-line bg-white lg:grid-cols-[minmax(0,1fr)_390px]"><section className="min-h-[600px] p-7">{step === 1 && <div><h2 className="text-lg font-semibold">Choose an audience</h2><p className="mb-5 text-sm text-[#71807a]">Select the segment this campaign should reach.</p><div className="grid gap-3 md:grid-cols-2">{segments.map((segment) => <button onClick={() => setSegmentId(segment.id)} key={segment.id} className={`rounded-md border p-4 text-left ${segmentId === segment.id ? "border-accent bg-[#f0f8f5]" : "border-line"}`}><strong className="text-sm">{segment.name}</strong><p className="mt-1 text-xs text-[#71807a]">{segment.description}</p><span className="mt-4 block text-lg font-semibold">{segment.customerCount}</span><span className="text-xs text-[#71807a]">estimated recipients</span></button>)}</div>{preview && <div className="mt-5"><span className="label">Sample customers</span><div className="mt-2 divide-y divide-line rounded-md border border-line">{preview.customers.slice(0, 5).map((customer) => <div key={customer.id} className="grid grid-cols-[1fr_120px_100px] px-3 py-2 text-sm"><span>{customer.name}</span><span className="text-[#71807a]">{customer.city}</span><strong>${Number(customer.totalOrderValue).toFixed(0)}</strong></div>)}</div></div>}</div>}
      {step === 2 && <div className="space-y-5"><div><label className="label">Campaign name</label><input className="input mt-1" value={name} onChange={(event) => setName(event.target.value)} /></div><div><label className="label">Channel</label><div className="mt-2 flex flex-wrap gap-2">{channels.map(({ value, icon: Icon }) => <button className={`btn ${channel === value ? "border-accent bg-[#eef7f3] text-accent" : ""}`} key={value} onClick={() => setChannel(value)}><Icon size={15} />{value}</button>)}</div></div><div><label className="label">Control message</label><textarea className="input mt-1 min-h-32 resize-none" value={message} onChange={(event) => setMessage(event.target.value)} /><p className="mt-1 text-xs text-[#7b8783]">Available variables: {"{{name}}"}, {"{{lastProduct}}"}</p></div><div className="rounded-md border border-line bg-[#f8faf9] p-4"><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={experimentEnabled} onChange={(event) => setExperimentEnabled(event.target.checked)} /> Run randomized A/B experiment</label>{experimentEnabled && <div className="mt-4 space-y-4"><div><label className="label">Hypothesis</label><input className="input mt-1" value={hypothesis} onChange={(event) => setHypothesis(event.target.value)} /></div><div><label className="label">AI treatment message</label><textarea className="input mt-1 min-h-28 resize-none" value={treatmentMessage} onChange={(event) => setTreatmentMessage(event.target.value)} /></div><p className="text-xs text-[#71807a]">Recipients are assigned 50/50 using a stable hash, preventing allocation drift during retries.</p></div>}</div></div>}
      {step === 3 && <div><h2 className="text-lg font-semibold">Review campaign</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="rounded-md bg-[#f2f5f3] p-5"><span className="label">Reach</span><strong className="mt-2 block text-3xl">{preview?.count ?? selected?.customerCount ?? 0}</strong><p className="text-xs text-[#71807a]">{selected?.name}</p></div><div className="rounded-md bg-[#f2f5f3] p-5"><span className="label">Estimated cost</span><strong className="mt-2 block text-3xl">${((preview?.count ?? selected?.customerCount ?? 0) * 0.02).toFixed(2)}</strong><p className="text-xs text-[#71807a]">Demo rate at $0.02/message</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-md border border-line p-5"><span className="label">Control</span><p className="mt-3 text-sm leading-6">{message.replace("{{name}}", "Maya").replace("{{lastProduct}}", "Vitamin C Serum")}</p></div>{experimentEnabled && <div className="rounded-md border border-accent bg-[#f0f8f5] p-5"><span className="label">AI treatment</span><p className="mt-3 text-sm leading-6">{treatmentMessage.replace("{{name}}", "Maya").replace("{{lastProduct}}", "Vitamin C Serum")}</p></div>}</div></div>}
      {step === 4 && <div><h2 className="text-lg font-semibold">Dispatch timing</h2><div className="mt-5 flex gap-2"><button className={`btn ${scheduleMode === "now" ? "border-accent bg-[#eef7f3] text-accent" : ""}`} onClick={() => setScheduleMode("now")}><Send size={15} /> Launch now</button><button className={`btn ${scheduleMode === "later" ? "border-accent bg-[#eef7f3] text-accent" : ""}`} onClick={() => setScheduleMode("later")}><CalendarClock size={15} /> Schedule</button></div>{scheduleMode === "later" && <div className="mt-4 max-w-sm"><label className="label">Send date and time</label><input className="input mt-1" type="datetime-local" min={new Date().toISOString().slice(0, 16)} value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} /></div>}<div className="mt-5 space-y-3 rounded-md border border-line bg-[#f8faf9] p-4"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={scoreTargeting} onChange={(event) => setScoreTargeting(event.target.checked)} /> Send only to top-scored customers</label>{scoreTargeting && <label className="block text-sm">Top {targetPercentage}%<input className="mt-2 w-full accent-[#147d64]" type="range" min="5" max="100" step="5" value={targetPercentage} onChange={(event) => setTargetPercentage(Number(event.target.value))} /></label>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={recommendedChannel} onChange={(event) => setRecommendedChannel(event.target.checked)} /> Automatically apply recommended channel</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={recommendedTime} onChange={(event) => setRecommendedTime(event.target.checked)} /> Automatically apply per-customer send hour</label></div><p className="mt-5 max-w-lg text-sm text-[#71807a]">Opt-outs, suppressions, and weekly frequency caps are enforced before jobs are created.</p>{submitError && <p className="mt-3 text-sm text-red-700">{submitError}</p>}<button onClick={() => create.mutate()} disabled={create.isPending || (scheduleMode === "later" && !scheduledAt)} className="btn btn-primary mt-6"><Send size={16} />{create.isPending ? "Preparing..." : scheduleMode === "later" ? "Schedule campaign" : "Launch now"}</button></div>}
      <div className="mt-10 flex justify-between border-t border-line pt-5"><button className="btn" disabled={step === 1} onClick={() => setStep((current) => Math.max(1, current - 1))}><ArrowLeft size={15} /> Back</button>{step < 4 && <button className="btn btn-primary" disabled={step === 1 && !segmentId} onClick={() => setStep((current) => Math.min(4, current + 1))}>Continue <ArrowRight size={15} /></button>}</div></section><AIChatSidebar onDraft={(draft) => { if (draft.template) setMessage(draft.template); if (isChannel(draft.channel)) setChannel(draft.channel); setStep(2); }} onRecommendation={(recommended) => { if (isChannel(recommended)) setChannel(recommended); }} /></div>
  </div>;
}
